// Generated by gencpp from file commande/Etat.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_ETAT_H
#define COMMANDE_MESSAGE_ETAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande
{
template <class ContainerAllocator>
struct Etat_
{
  typedef Etat_<ContainerAllocator> Type;

  Etat_()
    : x(0.0)
    , y(0.0)
    , cap(0.0)
    , u(0.0)
    , v(0.0)
    , r(0.0)  {
    }
  Etat_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , cap(0.0)
    , u(0.0)
    , v(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _cap_type;
  _cap_type cap;

   typedef double _u_type;
  _u_type u;

   typedef double _v_type;
  _v_type v;

   typedef double _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::commande::Etat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande::Etat_<ContainerAllocator> const> ConstPtr;

}; // struct Etat_

typedef ::commande::Etat_<std::allocator<void> > Etat;

typedef boost::shared_ptr< ::commande::Etat > EtatPtr;
typedef boost::shared_ptr< ::commande::Etat const> EtatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande::Etat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande::Etat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'commande': ['/home/dembele/Projet_indus/projet_catamaran/ROScata/src/commande/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande::Etat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande::Etat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::Etat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::Etat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::Etat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::Etat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande::Etat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6c594b1e53eca8aa163d299ac747d00";
  }

  static const char* value(const ::commande::Etat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6c594b1e53eca8aULL;
  static const uint64_t static_value2 = 0xa163d299ac747d00ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande::Etat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande/Etat";
  }

  static const char* value(const ::commande::Etat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande::Etat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 cap\n"
"float64 u\n"
"float64 v\n"
"float64 r\n"
;
  }

  static const char* value(const ::commande::Etat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande::Etat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.cap);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Etat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande::Etat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande::Etat_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "cap: ";
    Printer<double>::stream(s, indent + "  ", v.cap);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_MESSAGE_ETAT_H
