// Generated by gencpp from file commande/Waypoint.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_WAYPOINT_H
#define COMMANDE_MESSAGE_WAYPOINT_H

#include <ros/service_traits.h>


#include <commande/WaypointRequest.h>
#include <commande/WaypointResponse.h>


namespace commande
{

struct Waypoint
{

typedef WaypointRequest Request;
typedef WaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Waypoint
} // namespace commande


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commande::Waypoint > {
  static const char* value()
  {
    return "35dc34f29260882589d46e46eaa3c0a6";
  }

  static const char* value(const ::commande::Waypoint&) { return value(); }
};

template<>
struct DataType< ::commande::Waypoint > {
  static const char* value()
  {
    return "commande/Waypoint";
  }

  static const char* value(const ::commande::Waypoint&) { return value(); }
};


// service_traits::MD5Sum< ::commande::WaypointRequest> should match 
// service_traits::MD5Sum< ::commande::Waypoint > 
template<>
struct MD5Sum< ::commande::WaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::commande::Waypoint >::value();
  }
  static const char* value(const ::commande::WaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande::WaypointRequest> should match 
// service_traits::DataType< ::commande::Waypoint > 
template<>
struct DataType< ::commande::WaypointRequest>
{
  static const char* value()
  {
    return DataType< ::commande::Waypoint >::value();
  }
  static const char* value(const ::commande::WaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commande::WaypointResponse> should match 
// service_traits::MD5Sum< ::commande::Waypoint > 
template<>
struct MD5Sum< ::commande::WaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commande::Waypoint >::value();
  }
  static const char* value(const ::commande::WaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande::WaypointResponse> should match 
// service_traits::DataType< ::commande::Waypoint > 
template<>
struct DataType< ::commande::WaypointResponse>
{
  static const char* value()
  {
    return DataType< ::commande::Waypoint >::value();
  }
  static const char* value(const ::commande::WaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMANDE_MESSAGE_WAYPOINT_H
