// Generated by gencpp from file commande/WaypointRequest.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_WAYPOINTREQUEST_H
#define COMMANDE_MESSAGE_WAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande
{
template <class ContainerAllocator>
struct WaypointRequest_
{
  typedef WaypointRequest_<ContainerAllocator> Type;

  WaypointRequest_()
    : enter(false)  {
    }
  WaypointRequest_(const ContainerAllocator& _alloc)
    : enter(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enter_type;
  _enter_type enter;





  typedef boost::shared_ptr< ::commande::WaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande::WaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointRequest_

typedef ::commande::WaypointRequest_<std::allocator<void> > WaypointRequest;

typedef boost::shared_ptr< ::commande::WaypointRequest > WaypointRequestPtr;
typedef boost::shared_ptr< ::commande::WaypointRequest const> WaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande::WaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande::WaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'commande': ['/home/dembele/Projet_indus/projet_catamaran/ROScata/src/commande/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande::WaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande::WaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::WaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::WaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::WaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::WaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2627da596b51defe164212448220e93";
  }

  static const char* value(const ::commande::WaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2627da596b51defULL;
  static const uint64_t static_value2 = 0xe164212448220e93ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande/WaypointRequest";
  }

  static const char* value(const ::commande::WaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"bool enter\n"
;
  }

  static const char* value(const ::commande::WaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande::WaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande::WaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande::WaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "enter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_MESSAGE_WAYPOINTREQUEST_H
